apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: label-1project
            operator: In
            values:
            - roboshop
  containers:
  - name: with-node-affinity
    image: nginx
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "roboshop"
    effect: "NoExecute"
  